#!/usr/local/bin/fish

set FUNC darksky_one
set PROFILE aklambda

rm one.zip
zip -r one.zip index.js node_modules package.json hello-1.0.0-linux-x86_64 hello.rb

aws lambda update-function-code --region us-west-2 --profile $PROFILE --function-name $FUNC --zip-file fileb://one.zip
#aws lambda create-function --region us-west-2 --runtime nodejs6.10 --role arn:aws:iam::268578439486:role/service-role/slackGoogleRole --profile $PROFILE --function-name $FUNC --handler index.handler --timeout 10 --memory-size 1024 --zip-file fileb://one.zip
